### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by wsoyka-tgm** [TGM-HIT/eqep-service#14]
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wolfram/anaconda3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/wolfram/eqep/eqep-service/service/calculate/memrestricted.py", line 65, in run
    self.notify_observers(job)
  File "/home/wolfram/eqep/eqep-service/service/calculate/observer.py", line 35, in notify_observers
    observer.notify(obj)
  File "/home/wolfram/eqep/eqep-service/service/pinstance.py", line 136, in notify
    s = self.smetas[job.order]
IndexError: list index out of range`

don't know why this happens - restart of the service is required to solve it

**Comment by gye-tgm** [comment]
If the Calculator (see the class) gets stopped it still has some momentum (meaning it has some open jobs), and it will try to notify the old instances with the old finished jobs. I've added a session id to both the jobs and the project metadata to thwart this issue
